name: education_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # A dart package that helps to implement value based equality without needing override == and hashCode methods.
  equatable: ^2.0.7
  # Functional Programming in Dart
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true